name: Dependencies

on:
  workflow_run:
    workflows: ["CI"]
    types: [completed]

jobs:
  act:
    uses: oneshotmn/.github/.github/workflows/deps.yml@main
    secrets:
      app-id: ${{ secrets.ONESHOT_PR_APP_ID }}
      app-private-key: ${{ secrets.ONESHOT_PR_PRIVATE_KEY }}
