name: TrigTest

on:
  workflow_dispatch:

jobs:
  act:
    uses: ./.github/workflows/deps-inline.yml
    secrets:
      app-id: ${{ secrets.ONESHOT_PR_APP_ID }}
      app-private-key: ${{ secrets.ONESHOT_PR_PRIVATE_KEY }}
